/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

export const medicalTerms = [
{
    "id": "term_myalgia",
    "primaryTerm": "Myalgia",
    "primaryAbbr": null,
    "variants": ["Muscle ache"],
    "definition": "Muscle pain.",
    "category": "Symptom",
    "example": "Patient reports diffuse myalgia for 3 days.",
    "etymology": "Greek: myos (muscle) + algos (pain)",
    "snomedCtId": "68962001",
    "icd10Code": "M79.1",
    "notes": "A common symptom of many illnesses, including infections, autoimmune disorders, and injuries."
  },
  {
    "id": "term_itis",
    "primaryTerm": "-itis",
    "primaryAbbr": null,
    "variants": [],
    "definition": "Inflammation of a specific part of the body.",
    "category": "Suffix",
    "example": "Appendicitis (inflammation of the appendix), Gastritis (inflammation of the stomach).",
    "etymology": "Greek: -itis (pertaining to inflammation)",
    "snomedCtId": "404684003",
    "icd10Code": null,
    "notes": "This suffix is attached to a root word to denote inflammation of that root part (e.g., nephr- + -itis = nephritis)."
  },
  {
    "id": "term_ectomy",
    "primaryTerm": "-ectomy",
    "primaryAbbr": null,
    "variants": [],
    "definition": "Surgical removal of something.",
    "category": "Suffix",
    "example": "Appendectomy (removal of the appendix).",
    "etymology": "Greek: ektomē (a cutting out)",
    "snomedCtId": "129304002",
    "icd10Code": null,
    "notes": "A common suffix used in surgical procedure terminology."
  },
  {
    "id": "term_brady",
    "primaryTerm": "Brady-",
    "primaryAbbr": null,
    "variants": [],
    "definition": "Slow.",
    "category": "Prefix",
    "example": "Bradycardia (slow heart rate).",
    "etymology": "Greek: bradys (slow)",
    "snomedCtId": null,
    "icd10Code": null,
    "notes": "Used to describe a rate that is slower than normal."
  },
  {
    "id": "term_tachy",
    "primaryTerm": "Tachy-",
    "primaryAbbr": null,
    "variants": [],
    "definition": "Fast, rapid.",
    "category": "Prefix",
    "example": "Tachycardia (fast heart rate).",
    "etymology": "Greek: tachys (swift)",
    "snomedCtId": null,
    "icd10Code": null,
    "notes": "Used to describe a rate that is faster than normal."
  },
  {
    "id": "term_nephro",
    "primaryTerm": "Nephr/o-",
    "primaryAbbr": null,
    "variants": [],
    "definition": "Pertaining to the kidney.",
    "category": "Root Word / Prefix",
    "example": "Nephrology (study of kidneys), Nephritis (inflammation of the kidney).",
    "etymology": "Greek: nephros (kidney)",
    "snomedCtId": null,
    "icd10Code": null,
    "notes": "A foundational root for many kidney-related medical terms."
  },
  {
    "id": "term_hemo",
    "primaryTerm": "Hem/o-, Hemat/o-",
    "primaryAbbr": null,
    "variants": [],
    "definition": "Pertaining to blood.",
    "category": "Root Word / Prefix",
    "example": "Hematology (study of blood), Hemoptysis (coughing up blood).",
    "etymology": "Greek: haima (blood)",
    "snomedCtId": null,
    "icd10Code": null,
    "notes": "A foundational root for many blood-related medical terms."
  },
  {
    "id": "term_dysphagia",
    "primaryTerm": "Dysphagia",
    "primaryAbbr": null,
    "variants": [],
    "definition": "Difficulty swallowing.",
    "category": "Symptom",
    "example": "Patient complains of dysphagia with solids more than liquids.",
    "etymology": "Greek: dys- (bad, difficult) + phagein (to eat)",
    "snomedCtId": "40739000",
    "icd10Code": "R13.10",
    "notes": "Can be a symptom of many different medical conditions affecting the throat or esophagus."
  },
  {
    "id": "term_arthralgia",
    "primaryTerm": "Arthralgia",
    "primaryAbbr": null,
    "variants": ["Joint ache"],
    "definition": "Joint pain.",
    "category": "Symptom",
    "example": "Associated symptoms include arthralgia and morning stiffness.",
    "etymology": "Greek: arthron (joint) + algos (pain)",
    "snomedCtId": "57676002",
    "icd10Code": "M25.50",
    "notes": "Distinguished from arthritis, which involves inflammation of the joint. Arthralgia is pain without inflammation."
  },
  {
    "id": "term_osteoporosis",
    "primaryTerm": "Osteoporosis",
    "primaryAbbr": null,
    "variants": [],
    "definition": "A condition characterized by a decrease in the density of bone, decreasing its strength and resulting in fragile bones.",
    "category": "Condition",
    "example": "Risk factors for osteoporosis include age and low calcium intake.",
    "etymology": "Greek: osteon (bone) + poros (pore, passage)",
    "snomedCtId": "64859006",
    "icd10Code": "M81.0",
    "notes": "Leads to an increased risk of fractures. Diagnosis is often made using a bone density scan (DEXA)."
  },
  {
    "id": "term_leukopenia",
    "primaryTerm": "Leukopenia",
    "primaryAbbr": null,
    "variants": [],
    "definition": "A reduction in the number of white blood cells (leukocytes) in the blood.",
    "category": "Condition / Lab Finding",
    "example": "Chemotherapy can cause leukopenia, increasing infection risk.",
    "etymology": "Greek: leukos (white) + penia (deficiency)",
    "snomedCtId": "84828003",
    "icd10Code": "D70.9",
    "notes": "This condition makes individuals more susceptible to infections."
  },
  {
    "id": "term_anuria",
    "primaryTerm": "Anuria",
    "primaryAbbr": null,
    "variants": [],
    "definition": "Nonpassage of urine, in practice is defined as passage of less than 100 milliliters of urine in a day.",
    "category": "Symptom / Condition",
    "example": "Anuria is a critical sign of kidney failure.",
    "etymology": "Greek: an- (without) + ouron (urine)",
    "snomedCtId": "14761003",
    "icd10Code": "R34",
    "notes": "Represents a severe malfunction of the kidneys."
  },
  {
    "id": "term_hematuria",
    "primaryTerm": "Hematuria",
    "primaryAbbr": null,
    "variants": [],
    "definition": "The presence of red blood cells in the urine.",
    "category": "Symptom / Lab Finding",
    "example": "Gross hematuria was observed, prompting urological consultation.",
    "etymology": "Greek: haima (blood) + ouron (urine)",
    "snomedCtId": "34436003",
    "icd10Code": "R31.9",
    "notes": "Can be microscopic (not visible to the naked eye) or gross (visible). It requires medical evaluation to determine the cause."
  },
  {
    "id": "term_pathology",
    "primaryTerm": "Pathology",
    "primaryAbbr": null,
    "variants": [],
    "definition": "The study of the causes and effects of disease or injury.",
    "category": "Field of Study",
    "example": "The pathology report confirmed the diagnosis.",
    "etymology": "Greek: pathos (suffering, disease) + logia (study of)",
    "snomedCtId": "62427003",
    "icd10Code": null,
    "notes": "A major field in modern medicine and diagnosis."
  },
  {
    "id": "term_endoscopy",
    "primaryTerm": "Endoscopy",
    "primaryAbbr": null,
    "variants": [],
    "definition": "A nonsurgical procedure used in medicine to examine a person's digestive tract.",
    "category": "Procedure",
    "example": "An upper endoscopy was performed to evaluate the dysphagia.",
    "etymology": "Greek: endon (within) + skopein (to look at)",
    "snomedCtId": "71700008",
    "icd10Code": null,
    "notes": "Uses an endoscope, a flexible tube with a light and camera attached to it."
  }
];
