name: rmed_pro
description: A premier, cross-platform medical reference and calculator application.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Architecture
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.0

  # Data Modeling & Persistence
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  
  # Utility
  flutter_lints: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/json/
